version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: location
    ports: 
    - 5432:5432
  redis:
    image: redis
    ports: 
      - 6379:6379