version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: location
    ports: 
    - 5432:5432